study_config.yml 

# studies/MODEL-AD-Example/study_config.yml
# Configuration file for MODEL-AD Example Study

adelID: "ADEL123456"
studyName: "MODEL-AD Example Study"
synIDs:
  study: "syn51713891"
metadata: "syn23456789"
assays:
  Proteomics:
    raw_data: "syn34567890"
    processed_data: "syn45678901"
  Genomics:
    raw_data: "syn56789012"
    processed_data: "syn67890123"
