# studies_config.yml
# This file links to individual study configuration files for each study in the MODEL-AD project.

config_path_format: "modelad/studies/{name}/study_config.yml"

studies:
  - name: "Jax.IU.Pitt_LOAD2.PrimaryScreen"
    synID: "syn22086730"

  - name: "UCI_ABCA7"
    synID: "syn27207345"

  - name: "UCI_CCLines"
    synID: "syn51713891"

  - name: "Jax.IU.Pitt_Verubecestat_5XFAD"
    synID: "syn21863375"

  - name: "UCI_5XFAD"
    synID: "syn16798076"

  - name: "Jax.IU.Pitt_LOAD2"
    synID: ""

  - name: "MODEL-AD-Example"
    synID: "syn61377081"
