study_config.yml 

# Study Identifiers
adelID: ""
admID: ""
studyID: ""

# Study Details
studyName: ""
program: ""
module: ""
studyFocus: ""
grantNumber: ""
leadPI: ""
institution: ""
species: ""
specimenType: ""
dataType: ""
fundingAgency: ""

# Data Liaison Information
dataLiaisonName: ""
dataLiaisonEmail: ""

# Synapse Information
synIDs:
  study: ""
  staging: ""
  dataSurveyInventory: "" # Insert synID or link to external documentation
  projectDCA: "" # Provide Synapse Project for DCA

# Metadata Synapse IDs (optional)
metadata:
  general: ""
  individual: ""
  biospecimen: ""

# Assay-Specific Synapse IDs (optional)
assays:
  {assay_name}:
    raw_data: ""
    processed_data: ""
    metadata: ""
