# study_config.yaml
# Example configuration to create usable documentation

                # Staging ID
admID: "https://sagebionetworks.jira.com/browse/ADM-118"
adelID: ""
studyID: "Jax.IU.Pitt_LOAD2" # Unique identifier for the study
studyName: "The Jax.IU.Pitt LOAD2 Study"  # Descriptive name of the study
program: "MODEL-AD"                        # Program under which the study is conducted
module: "ADKP"                             # Module associated with the study
studyFocus: "Alzheimer Disease"            # Focus area of the study
grantNumber: "U54 AG054345"                 # Grant number
leadPI: "Greg Carter"                          # Name of the Principal Investigator or Group
institution: "Jackson Labs"  # Institution conducting the study
species: "Mouse"                           # Species investigated
specimenType: "Brain, Blood"               # Tissue or sample type collected
dataType: "Gene Expression, Immunoassay, Metabolomics, Proteomics, Imaging"   # Methods or assays used
synID: "syn51534997"                       # Synapse ID for the study
stagingID: "syn51535045"   
source: "https://adknowledgeportal.synapse.org/Explore/Studies/DetailsPage/StudyDetails?Study=syn51534997"  # Source URL
fundingAgency: "NIA"                       # Funding agency
