# study_config.yml

study:
  name: "Jax.IU.Pitt_LOAD2"
  ids:
    adel: "https://sagebionetworks.jira.com/browse/ADEL-49"
    adm: "https://sagebionetworks.jira.com/browse/ADM-118"
    syn: "syn51534997"
    staging: "syn51535045"
  existing: false
  info:
    grant: "U54AG054345"
    portal: "ADKP"
    program: "MODEL-AD"
    focus: "Gene Expression"
    pi: "Bruce Lamb"
    agency: "NIA"
  institution:
    name: "Indiana University School of Medicine"
    contact: "catrina.spruce@jax.org"
  specimens:
    species: "Mouse"
    types:
      - "Brain"
      - "Blood"
  metadata:
    general: "syn51745755"
    individual: "syn34228037"
    biospecimen: "syn34228034"
    RNASeq: "syn51708695"
    TMTquantitation: "syn62012514"
    immunoassay: "syn62012516"
    metabolomics: "syn62012515"
    id_key: "syn51441046"
  data:
    behavioral: "syn51745788"
    RNASeq:
      raw: "syn51748057"
      processed: "syn51748058"
    imaging: "syn53360242"
    immunoassay: "syn51904331"
    metabolomics: "syn51748055"
    proteomics: "syn51745781"

