# study_config.yaml
# Example configuration to create usable documentation

studyID: "UCI_CCLines"                     # Unique identifier for the study
studyName: "The UCI Collaborative Cross Lines Study"  # Descriptive name of the study
program: "MODEL-AD"                        # Program under which the study is conducted
module: "ADKP"                             # Module associated with the study
studyFocus: "Alzheimer Disease"            # Focus area of the study
grantNumber: "U54AG054349"                 # Grant number
leadPI: "UCI_TMF"                          # Name of the Principal Investigator or Group
institution: "University of California - Irvine"  # Institution conducting the study
species: "Mouse"                           # Species investigated
specimenType: "Brain, Blood"               # Tissue or sample type collected
dataType: "Gene Expression, Immunoassay"   # Methods or assays used
synID: "syn51713891"                       # Synapse ID for the study
source: "https://adknowledgeportal.synapse.org/Explore/Studies/DetailsPage/StudyDetails?Study=syn51713891"  # Source URL
fundingAgency: "NIA"                       # Funding agency
fileviewName: "MODEL-AD_UCI_CCLines"
parentID: "syn2580853"
scopeID: 
  - "syn51713891" # UCI_CCLines
  - "syn51713897" # metadata
  - "syn51713902" # data 1
  # - "syn58841752" # data 2
  - "syn27207345" # UCI_ABCA7
  - "syn27207357" # abca7 metadata
  # - "syn53606335" # comparison - abca7 data 1
  # - "syn53616447" # comparison - abca7 data 2
