# study_config_template.yaml

study:
  name: "Study_Name"
  ids:
    adel: "ADEL_URL"
    adm: "ADM_URL"
    syn: "SYN_ID"
    staging: "STAGING_ID"
    view: "VIEW_ID"
  existing: false  # true or false
  info:
    grant: "Grant_Number"
    portal: "Portal_Name"
    program: "Program_Name"
    module: "Module_Name"
    focus: "Study_Focus"
    pi: "Principal_Investigator"
    agency: "Funding_Agency"
  institution:
    name: "Institution_Name"
    contact: "Contact_Email"
  specimens:
    species: "Species_Used"
    types: ["Specimen_Type1", "Specimen_Type2"]
  metadata:
    general: "General_Metadata_ID"
    individual: "Individual_Metadata_ID"
    biospecimen: "Biospecimen_Metadata_ID"
  assays:
    Assay_Name:
      raw: "Raw_Data_ID"
      processed: "Processed_Data_ID"
      meta: "Metadata_ID"
