# study_config.yaml

study:
  name: "Jax.IU.Pitt_LOAD2.PrimaryScreen"
  ids:
    adel: "https://sagebionetworks.jira.com/servicedesk/customer/portal/12/ADEL-261"
    adm: "https://sagebionetworks.jira.com/browse/ADM-2659"
    syn: "syn58863147"
    staging: "syn58863153"
  metadata:
    general: "syn59479679"
    individual: "syn53282594"
    biospecimen: "syn53282599"
    RNASeq: "syn53710873"
  data:
    RNASeq:
      raw: "syn59479899"
      processed: "syn59479678"
  info:
    grant: "U54AG054345"
    portal: "ADKP"
    program: "MODEL-AD"
    pi: "Bruce Lamb"
    contact: "catrina.spruce@jax.org"
  specimens:
    species: "Mouse"
    types: ["Brain", "Blood"]
