# Study Identifiers
adelID: "https://sagebionetworks.jira.com/servicedesk/customer/portal/12/ADEL-261"
admID: "https://sagebionetworks.jira.com/browse/ADM-2659"
studyID: "Jax.IU.Pitt_LOAD2.PrimaryScreen"

# Study Details
studyName: "The Jax.IU.Pitt LOAD2 PrimaryScreen Study"
program: "MODEL-AD"
module: "ADKP"
studyFocus: "Alzheimer Disease"
grantNumber: "U54 AG054345"
leadPI: "Bruce Lamb"
institution: "Indiana University School of Medicine"
species: "Mouse"
specimenType: "Brain, Blood"
dataType: "Gene Expression"
synID: "syn58863147"
source: "https://adknowledgeportal.synapse.org/Explore/Studies/DetailsPage/StudyDetails?Study=syn58863147"
fundingAgency: "NIA"

# Data Liaison Information
dataLiaisonName: "Catrina Spruce"
dataLiaisonEmail: "catrina.spruce@jax.org"

# Study Information
existingStudy: "No"
dataSurveyInventory: "" # Insert synID or link to external documentation
synapseProjectDCA: "" # Provide Synapse Project for DCA
stagingSynID: "syn58863153"
dataReleaseDate: "" # Provide in format # Month YEAR
manuscriptIssue: "" # Provide if applicable
additionalNotes: "" # Internal DCC notes
cohortSource: "" # Provide if applicable

# Optional Features
# citation: "10.1234/example.doi"

